root = "."

[build]
cmd = "go build -o ./tmp/reader ./cmd/reader"
bin = "./tmp/reader"
delay = 1000
rerun_delay = 500
poll = false
poll_interval = 0

exclude_dir = ["tmp", "vendor", "testdata"]
include_ext = ["go"]
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
